package review

import (
	"strings"
	"testing"

	"github.com/your-company/agentic-code-review/internal/github"
)

// ARC's previous review is already accounted for by the publication history.
// Feeding its own words back in would let it treat its earlier opinion as
// independent evidence for the same opinion.
func TestWithDiscussionExcludesARCsOwnComments(t *testing.T) {
	ctx := WithDiscussion(Context{}, []github.Comment{
		{Kind: github.CommentConversation, Author: "arc-bot",
			Body: "## ARC Agentic Code Review\n\nReviewed commit: `abc`\n\n<!-- arc-review:v1 head=abc -->"},
		{Kind: github.CommentInline, Author: "arc-bot", Path: "a.go", Line: 4,
			Body: "**HIGH · COR-001 — Something**\n\nGenerated by ARC."},
		{Kind: github.CommentConversation, Author: "maria", Body: "This is deliberate."},
	})

	if ctx.Discussion.Count() != 1 {
		t.Fatalf("comments = %+v, want only the human one", ctx.Discussion.Comments)
	}
	if ctx.Discussion.Comments[0].Author != "maria" {
		t.Errorf("kept comment = %+v", ctx.Discussion.Comments[0])
	}
	for _, comment := range ctx.Discussion.Comments {
		if strings.Contains(comment.Body, "ARC") {
			t.Errorf("an ARC comment survived: %q", comment.Body)
		}
	}
}

// A human quoting ARC is still a human comment; exclusion keys on ARC's own
// markers and signature, which a person discussing a finding does not reproduce.
func TestWithDiscussionKeepsHumanRepliesAboutFindings(t *testing.T) {
	ctx := WithDiscussion(Context{}, []github.Comment{
		{Kind: github.CommentInline, Author: "sam", Path: "a.go", Line: 4,
			Body: "Re COR-001: intentional, the caller already validates this."},
	})

	if ctx.Discussion.Count() != 1 {
		t.Fatalf("comments = %+v, want the human reply kept", ctx.Discussion.Comments)
	}
}

func TestWithDiscussionPreservesLocationAndKind(t *testing.T) {
	ctx := WithDiscussion(Context{}, []github.Comment{
		{Kind: github.CommentInline, Author: "maria", Path: "internal/pay/retry.go", Line: 84,
			Body: "here", Truncated: true},
	})

	comment := ctx.Discussion.Comments[0]
	if comment.Kind != "inline" || comment.Location() != "internal/pay/retry.go:84" || !comment.Truncated {
		t.Errorf("comment = %+v", comment)
	}
}

func TestWithDiscussionOnNoComments(t *testing.T) {
	if ctx := WithDiscussion(Context{}, nil); ctx.Discussion.Count() != 0 {
		t.Errorf("discussion = %+v, want empty", ctx.Discussion)
	}
}
