package publish

import (
	"fmt"
	"strings"

	"github.com/your-company/agentic-code-review/internal/contextselect"
	"github.com/your-company/agentic-code-review/internal/findings"
)

// Rendering bounds. GitHub accepts a large comment body, but a comment nobody can
// read is not a review, so the ceilings here are well under the API's.
const (
	// MaxInlineCommentBytes bounds one inline comment.
	MaxInlineCommentBytes = 8 * 1024

	// MaxReviewBodyBytes bounds the review body. It matters most when many findings
	// land in the body because nothing could be attached to a line.
	MaxReviewBodyBytes = 60 * 1024

	// maxEvidenceDetailBytes is the first shortening step applied to an oversized
	// comment: details are trimmed before anything structural is touched.
	maxEvidenceDetailBytes = 300

	// maxEvidenceItems is how many evidence lines survive the later steps.
	maxEvidenceItems = 2

	// truncationNote marks text this renderer shortened.
	truncationNote = "…"
)

// Fixed strings in a published review. They are constants so output and tests cannot
// drift apart.
const (
	reviewHeading = "## ARC Agentic Code Review"
	signature     = "Generated by ARC."

	// noInlineFindings is what the inline section says when nothing could be attached
	// to a line. Saying so explicitly matters: silence would read as "nothing found".
	noInlineFindings = "None."

	// analysisUnavailable is what the deterministic-analysis section says when no
	// checks ran, which happens when no local checkout was provided.
	analysisUnavailable = "Not available — local repository was not provided."
)

// Renderer produces the exact Markdown that will be published.
//
// The model never writes what appears on GitHub. It supplies structured findings; this
// turns them into text. That separation is what makes the output predictable, keeps
// model-controlled prose out of the document structure, and lets the size bound be
// enforced by shortening evidence rather than by hoping the model was brief.
type Renderer struct{}

// NewRenderer returns a Renderer.
func NewRenderer() Renderer { return Renderer{} }

// InlineComment renders one finding as an inline review comment.
//
// If the full rendering exceeds MaxInlineCommentBytes, evidence is shortened in fixed
// steps until it fits. The identity of the finding — ID, severity, title, problem,
// impact, suggestion, and evidence strength — is never shortened away, because those are what
// make the comment actionable.
func (r Renderer) InlineComment(finding findings.Finding) string {
	// The hidden marker is what lets a human reply be matched back to this exact
	// finding on a later run. It is appended after the size check for the same
	// reason the review body's markers are: a comment that lost its identity
	// cannot be answered, and would be published again from scratch.
	marker := "\n" + RenderFingerprintMarker(finding) + "\n"
	budget := MaxInlineCommentBytes - len(marker)

	for _, level := range []evidenceDetail{
		evidenceFull, evidenceShortDetails, evidenceSourcesOnly, evidenceFewest, evidenceNone,
	} {
		body := renderComment(finding, level)
		if len(body) <= budget {
			return body + marker
		}
	}

	// Unreachable for a validated finding: the field limits in internal/findings bound
	// the preserved sections well below this ceiling. The clamp exists so an oversized
	// body can never be sent, whatever changes upstream.
	return clamp(renderComment(finding, evidenceNone), budget) + marker
}

// evidenceDetail is how much of a finding's evidence a rendering includes.
type evidenceDetail int

const (
	evidenceFull evidenceDetail = iota
	evidenceShortDetails
	evidenceSourcesOnly
	evidenceFewest
	evidenceNone
)

// renderComment renders a finding at one evidence level.
func renderComment(finding findings.Finding, level evidenceDetail) string {
	var out strings.Builder

	fmt.Fprintf(&out, "**%s · %s — %s**\n\n", finding.Severity.Display(), finding.ID, oneLine(finding.Title))
	fmt.Fprintf(&out, "%s\n\n", strings.TrimSpace(finding.Problem))
	fmt.Fprintf(&out, "**Impact:** %s\n", strings.TrimSpace(finding.Impact))

	if evidence := renderEvidence(finding.Evidence, level); evidence != "" {
		out.WriteString("\n" + evidence)
	}

	fmt.Fprintf(&out, "\n**Suggestion:** %s\n", strings.TrimSpace(finding.Suggestion))
	fmt.Fprintf(&out, "\nEvidence strength: %s\n", finding.EvidenceStrength().Display())

	return out.String()
}

// renderEvidence renders the evidence block at the given level of detail.
func renderEvidence(evidence []findings.Evidence, level evidenceDetail) string {
	if len(evidence) == 0 || level == evidenceNone {
		return ""
	}

	items := evidence
	if level == evidenceFewest && len(items) > maxEvidenceItems {
		items = items[:maxEvidenceItems]
	}

	var out strings.Builder
	out.WriteString("**Evidence**\n")

	for _, item := range items {
		fmt.Fprintf(&out, "- `%s`", oneLine(item.Source))

		switch level {
		case evidenceFull:
			fmt.Fprintf(&out, " — %s", oneLine(item.Detail))
		case evidenceShortDetails:
			fmt.Fprintf(&out, " — %s", clamp(oneLine(item.Detail), maxEvidenceDetailBytes))
		}
		out.WriteString("\n")
	}

	if omitted := len(evidence) - len(items); omitted > 0 {
		fmt.Fprintf(&out, "- %d further evidence item(s) omitted for length\n", omitted)
	}

	return out.String()
}

// ReviewInput is everything the review body reports on.
//
// It carries only what is safe to publish: a commit SHA, a ticket key, check outcomes,
// and findings. There is nowhere in this struct to put a token, a prompt, a Jira
// description, or a patch, so none of those can reach GitHub.
type ReviewInput struct {
	Plan    Plan
	HeadSHA string
	JiraKey string
	Checks  []contextselect.SelectedAnalysis
}

// ReviewBody renders the body of the published review.
//
// The hidden marker goes last, after the signature, so a human reading the review never
// notices it and a later run can still recognize this review as its own.
func (r Renderer) ReviewBody(input ReviewInput) string {
	var out strings.Builder

	out.WriteString(reviewHeading + "\n\n")

	if sha := strings.TrimSpace(input.HeadSHA); sha != "" {
		fmt.Fprintf(&out, "Reviewed commit: `%s`\n\n", sha)
	}
	if key := strings.TrimSpace(input.JiraKey); key != "" {
		fmt.Fprintf(&out, "Jira: `%s`\n\n", key)
	}

	writeDeltaSection(&out, input.Plan)
	writeResultSection(&out, input.Plan)
	writeInlineSection(&out, input.Plan)
	writeAdditionalSection(&out, input.Plan)
	writeAnalysisSection(&out, input.Checks)

	fmt.Fprintf(&out, "---\n%s\n", signature)

	// The markers are appended after clamping, never before it. They are what a
	// later run recognizes this review by: a body long enough to be cut would
	// otherwise lose its own identity and be republished as a duplicate.
	markers := fmt.Sprintf("\n%s\n%s\n",
		Marker{HeadSHA: input.HeadSHA}.Render(),
		MarkerFor(input.Plan).Render())

	return clamp(out.String(), MaxReviewBodyBytes-len(markers)) + markers
}

// writeDeltaSection reports how this review compares with the previous one.
//
// It leads the body because it is what a returning author wants first: what their
// last push resolved. The wording is deliberately "no longer reported" rather than
// "fixed" — ARC knows only what it is not saying any more, not that the underlying
// problem is gone.
func writeDeltaSection(out *strings.Builder, plan Plan) {
	delta := plan.Delta
	if !delta.Known {
		return
	}

	out.WriteString("### Since the previous review\n\n")
	fmt.Fprintf(out, "Compared with the review of `%s`:\n\n", delta.PreviousHeadSHA)

	if delta.Resolved > 0 {
		fmt.Fprintf(out, "- %d no longer reported\n", delta.Resolved)
	}
	if delta.Persisting > 0 {
		fmt.Fprintf(out, "- %d still reported\n", delta.Persisting)
	}
	if delta.New > 0 {
		fmt.Fprintf(out, "- %d newly reported\n", delta.New)
	}
	if delta.Resolved == 0 && delta.Persisting == 0 && delta.New == 0 {
		out.WriteString("- nothing reported either time\n")
	}
	if delta.Persisting > 0 {
		out.WriteString("\nFindings reported before are listed in the body rather than on the diff, " +
			"so this review does not comment again on lines already discussed.\n")
	}
	out.WriteString("\n")
}

// writeResultSection reports the count and the severity mix.
func writeResultSection(out *strings.Builder, plan Plan) {
	out.WriteString("### Result\n\n")

	publishable := plan.PublishableFindings()
	fmt.Fprintf(out, "%s\n", pluralFindings(len(publishable)))

	if len(publishable) > 0 {
		out.WriteString("\n")
		for _, severity := range findings.Severities() {
			if n := plan.CountBySeverity(severity); n > 0 {
				fmt.Fprintf(out, "- %d %s\n", n, severity)
			}
		}
	}

	if summary := strings.TrimSpace(plan.ResultSummary); summary != "" {
		fmt.Fprintf(out, "\n%s\n", summary)
	}
	out.WriteString("\n")
}

// writeInlineSection states how many findings were attached to lines, and says so
// explicitly when none were.
func writeInlineSection(out *strings.Builder, plan Plan) {
	out.WriteString("### Inline findings\n\n")

	switch len(plan.Inline) {
	case 0:
		out.WriteString(noInlineFindings + "\n\n")
	case 1:
		out.WriteString("1 finding was attached to a changed line.\n\n")
	default:
		fmt.Fprintf(out, "%d findings were attached to changed lines.\n\n", len(plan.Inline))
	}
}

// writeAdditionalSection renders the findings that have no inline comment.
//
// They appear in full rather than as a count: a finding that could not be placed on a
// line is not a lesser finding, it is one GitHub had nowhere to put.
func writeAdditionalSection(out *strings.Builder, plan Plan) {
	if len(plan.Summary) == 0 {
		return
	}

	out.WriteString("### Additional findings\n\n")

	for _, finding := range plan.Summary {
		fmt.Fprintf(out, "**%s · %s — %s**\n\n",
			finding.Severity.Display(), finding.ID, oneLine(finding.Title))
		fmt.Fprintf(out, "`%s`\n\n", finding.Location())
		fmt.Fprintf(out, "%s\n\n", strings.TrimSpace(finding.Problem))
		fmt.Fprintf(out, "**Impact:** %s\n\n", strings.TrimSpace(finding.Impact))
		fmt.Fprintf(out, "**Suggestion:** %s\n\n", strings.TrimSpace(finding.Suggestion))
		fmt.Fprintf(out, "Evidence strength: %s\n\n", finding.EvidenceStrength().Display())
	}
}

// writeAnalysisSection reports the deterministic checks, which are this tool's own
// evidence rather than anything a model produced. Only outcomes are published; command
// output stays local.
func writeAnalysisSection(out *strings.Builder, checks []contextselect.SelectedAnalysis) {
	out.WriteString("### Deterministic analysis\n\n")

	if len(checks) == 0 {
		out.WriteString(analysisUnavailable + "\n\n")
		return
	}

	for _, check := range checks {
		fmt.Fprintf(out, "- %s `%s`", checkIcon(check), check.Command)
		if check.Skipped {
			out.WriteString(" (skipped)")
		}
		if check.TimedOut {
			out.WriteString(" (timed out)")
		}
		out.WriteString("\n")
	}
	out.WriteString("\n")
}

// checkIcon renders a check's outcome compactly.
func checkIcon(check contextselect.SelectedAnalysis) string {
	switch {
	case check.Skipped:
		return "➖"
	case check.Passed:
		return "✅"
	default:
		return "❌"
	}
}

// pluralFindings renders a finding count with correct grammar.
func pluralFindings(count int) string {
	if count == 1 {
		return "1 finding"
	}
	return fmt.Sprintf("%d findings", count)
}

// oneLine collapses whitespace so a value cannot break the Markdown structure around
// it.
func oneLine(s string) string { return strings.Join(strings.Fields(s), " ") }

// clamp truncates s to at most limit bytes, on a rune boundary, appending a note when
// it had to cut.
func clamp(s string, limit int) string {
	if len(s) <= limit {
		return s
	}

	cut := limit - len(truncationNote)
	if cut < 0 {
		cut = 0
	}
	for cut > 0 && !isRuneStart(s[cut]) {
		cut--
	}
	return s[:cut] + truncationNote
}

// isRuneStart reports whether b begins a UTF-8 rune.
func isRuneStart(b byte) bool { return b&0xC0 != 0x80 }
