package contextselect

import (
	"path"
	"strings"

	"github.com/your-company/agentic-code-review/internal/technology"
)

// generatedMarkers are the conventional headers Go tools write into generated
// files. Matching is limited to the first few lines of a patch so a mention of
// the phrase deeper in a file cannot mislabel it.
var generatedMarkers = []string{
	"Code generated by",
	"DO NOT EDIT",
	"@generated",
	"autogenerated by",
}

// generatedLinesInspected bounds how far into a patch the marker search reads.
const generatedLinesInspected = 12

// Classify determines a file's kind from its path, using the patch only to spot
// generated-code markers. It is deterministic: the same inputs always give the
// same kind.
func Classify(filePath string, patch string) FileKind {
	clean := strings.TrimPrefix(path.Clean(filePath), "/")
	base := path.Base(clean)
	lowerBase := strings.ToLower(base)
	ext := strings.ToLower(path.Ext(base))

	// Vendored and generated code first: a vendored *.go file is not ordinary
	// source, and mislabelling it would inflate its priority.
	if isDependencyDirectory(clean) {
		return FileKindGenerated
	}
	if isGeneratedPath(clean, lowerBase) || hasGeneratedMarker(patch) {
		return FileKindGenerated
	}

	// Migrations are recognised by directory, whatever the file extension.
	if inDirectory(clean, "migrations", "migration", "migrate") {
		return FileKindMigration
	}

	if kind, ok := classifyByName(lowerBase); ok {
		return kind
	}

	// Documentation directories cover files that are not markdown.
	if inDirectory(clean, "docs", "doc") {
		return FileKindDocumentation
	}

	return classifyByExtension(ext, clean, lowerBase)
}

// classifyByName handles files identified by their exact name.
func classifyByName(lowerBase string) (FileKind, bool) {
	switch lowerBase {
	case "go.mod", "go.sum", "go.work", "go.work.sum",
		"package.json", "package-lock.json", "yarn.lock",
		"requirements.txt", "pipfile", "pipfile.lock", "poetry.lock",
		"gemfile", "gemfile.lock", "cargo.toml", "cargo.lock":
		return FileKindDependency, true

	case "dockerfile", "containerfile", "makefile", ".dockerignore", ".gitignore",
		".golangci.yml", ".golangci.yaml", ".editorconfig":
		return FileKindConfig, true

	case "readme.md", "readme", "changelog.md", "license", "license.md",
		"contributing.md", "agents.md", "code_of_conduct.md", "security.md":
		return FileKindDocumentation, true
	}

	if strings.HasPrefix(lowerBase, "dockerfile.") || strings.HasSuffix(lowerBase, ".dockerfile") {
		return FileKindConfig, true
	}
	if strings.HasPrefix(lowerBase, "docker-compose") {
		return FileKindConfig, true
	}

	return "", false
}

// classifyByExtension handles the remaining files by suffix.
func classifyByExtension(ext string, clean string, lowerBase string) FileKind {
	switch ext {
	case ".go":
		if strings.HasSuffix(lowerBase, "_test.go") {
			return FileKindTest
		}
		return FileKindSource

	case ".scala":
		// Scala marks a test by naming convention rather than by file suffix, so
		// FooSpec.scala and FooTest.scala are tests wherever they live, as is
		// anything under a test source root.
		if technology.IsScalaTest(clean) {
			return FileKindTest
		}
		return FileKindSource

	case ".sbt":
		// An .sbt file is build definition: configuration, not application code.
		return FileKindConfig

	case ".md", ".markdown", ".rst", ".adoc", ".txt":
		return FileKindDocumentation

	case ".yaml", ".yml", ".json", ".toml", ".ini", ".conf", ".cfg", ".env", ".properties":
		return FileKindConfig

	case ".sql":
		return FileKindMigration

	case ".proto":
		return FileKindSource

	case ".sh", ".bash":
		return FileKindConfig

	case ".js", ".jsx", ".ts", ".tsx", ".py", ".rb", ".java", ".kt", ".rs", ".c", ".h", ".cc", ".cpp", ".hpp", ".cs":
		if isTestPath(clean, lowerBase) {
			return FileKindTest
		}
		return FileKindSource
	}

	return FileKindUnknown
}

// isTestPath spots test files in the non-Go languages we classify loosely.
func isTestPath(clean string, lowerBase string) bool {
	for _, marker := range []string{"_test.", ".test.", "_spec.", ".spec."} {
		if strings.Contains(lowerBase, marker) {
			return true
		}
	}
	return inDirectory(clean, "test", "tests", "spec", "__tests__")
}

// isGeneratedPath spots generated files by naming convention.
func isGeneratedPath(clean string, lowerBase string) bool {
	suffixes := []string{
		".pb.go", ".pb.gw.go", "_pb2.py", ".generated.go", "_generated.go",
		"_gen.go", ".gen.go", "_string.go", ".min.js", ".min.css",
	}
	for _, suffix := range suffixes {
		if strings.HasSuffix(lowerBase, suffix) {
			return true
		}
	}

	return inDirectory(clean, "generated", "gen", ".gen")
}

// isDependencyDirectory spots checked-in third-party code.
func isDependencyDirectory(clean string) bool {
	return inDirectory(clean, "vendor", "node_modules", "third_party", "thirdparty")
}

// hasGeneratedMarker looks for a generated-code header near the top of a patch.
func hasGeneratedMarker(patch string) bool {
	if patch == "" {
		return false
	}

	lines := strings.SplitN(patch, "\n", generatedLinesInspected+1)
	if len(lines) > generatedLinesInspected {
		lines = lines[:generatedLinesInspected]
	}

	for _, line := range lines {
		// Only consider comment-ish lines, so a diff of prose about generated
		// code is not itself treated as generated.
		trimmed := strings.TrimLeft(line, "+- \t")
		if !strings.HasPrefix(trimmed, "//") && !strings.HasPrefix(trimmed, "#") && !strings.HasPrefix(trimmed, "/*") {
			continue
		}
		for _, marker := range generatedMarkers {
			if strings.Contains(trimmed, marker) {
				return true
			}
		}
	}
	return false
}

// inDirectory reports whether any path segment except the last equals one of
// names.
func inDirectory(clean string, names ...string) bool {
	segments := strings.Split(clean, "/")
	if len(segments) < 2 {
		return false
	}

	for _, segment := range segments[:len(segments)-1] {
		lower := strings.ToLower(segment)
		for _, name := range names {
			if lower == name {
				return true
			}
		}
	}
	return false
}

// ImportanceFor maps a file kind onto its retention priority.
func ImportanceFor(kind FileKind) Importance {
	switch kind {
	case FileKindSource, FileKindTest, FileKindMigration:
		return ImportanceHigh
	case FileKindConfig, FileKindDependency, FileKindUnknown:
		return ImportanceMedium
	case FileKindDocumentation, FileKindGenerated:
		return ImportanceLow
	default:
		return ImportanceMedium
	}
}

// rankBuildDefinition is the priority given to a build file whose language is under
// review. It sits above ordinary configuration and below changed source and tests: the
// build decides what the code compiles and tests against, but the code is still what
// is being reviewed.
const rankBuildDefinition = 3

// kindRank orders file kinds for budget allocation, lowest first. It encodes the
// selection priority: changed source, then tests, then migrations, then config,
// then anything unrecognised, then dependency manifests, then documentation, and
// generated output last.
func kindRank(kind FileKind) int {
	switch kind {
	case FileKindSource:
		return 1
	case FileKindTest:
		return 2
	case FileKindMigration:
		return 3
	case FileKindConfig:
		return 4
	case FileKindUnknown:
		return 5
	case FileKindDependency:
		return 6
	case FileKindDocumentation:
		return 7
	case FileKindGenerated:
		return 8
	default:
		return 9
	}
}

// reasonFor is the default explanation for selecting a file of this kind.
func reasonFor(kind FileKind) string {
	switch kind {
	case FileKindSource:
		return "changed source file"
	case FileKindTest:
		return "changed test file"
	case FileKindMigration:
		return "database migration"
	case FileKindConfig:
		return "configuration change"
	case FileKindDependency:
		return "dependency change"
	case FileKindDocumentation:
		return "documentation"
	case FileKindGenerated:
		return "generated file"
	default:
		return "changed file"
	}
}
